import A2UICore

public enum IconName: String, Codable, Sendable, Equatable, CaseIterable {
    case accountCircle
    case add
    case arrowBack
    case arrowForward
    case attachFile
    case calendarToday
    case call
    case camera
    case check
    case close
    case delete
    case download
    case edit
    case event
    case error
    case fastForward
    case favorite
    case favoriteOff
    case folder
    case help
    case home
    case info
    case locationOn
    case lock
    case lockOpen
    case mail
    case menu
    case moreVert
    case moreHoriz
    case notificationsOff
    case notifications
    case pause
    case payment
    case person
    case phone
    case photo
    case play
    case print
    case refresh
    case rewind
    case search
    case send
    case settings
    case share
    case shoppingCart
    case skipNext
    case skipPrevious
    case star
    case starHalf
    case starOff
    case stop
    case upload
    case visibility
    case visibilityOff
    case volumeDown
    case volumeMute
    case volumeOff
    case volumeUp
    case warning
}
